Readme updated
overture-stack/score pull request #344
Opened 2023-01-11 15:20 UTC by MitchellShiell

<h1>:newspaper: Updated to new format</h1>

- Also includes a standard code of conduct.md
- Two image files referenced in the readme

2023-05-10 18:10 UTC, dahiyaAD submitted a review, later dismissed
Looks good!

2023-05-11 19:43 UTC, joneubank requested changes
Bit more description to help out devs

2023-05-11 19:43 UTC, joneubank commented on README.md
> +- :construction: Developer documentation [Wiki](https://github.com/overture-stack/score/wiki) :construction:
```suggestion
- :construction: Developer documentation, including instructions for running Score from source can be found in the [Wiki](https://github.com/overture-stack/score/wiki) :construction:
```

2023-05-11 19:52 UTC, joneubank approved these changes

2023-05-11 19:52 UTC, merged